# All [labels] are made up of [type.id]
# Copy this into ./bin/Debug/ or ./bin/Release/ depending on the build you're using, once you have filled it out
[master.Master] # You can have multiple of these fields, just give them a different id, they control the bot via IM
uuid = "8852f73a-ab0f-4105-a7eb-e1bcdfcfd756" # Human avatar id
name = "Inusaito Kanya" # Human avatar legacy name

[bot.MyBot]
first_name = "MyBot" # Required
last_name = "Resident" # Required
password = "Password" # Required
# sit_on = "cae4ad0e-7eba-b6fa-d53c-4d7c4fbb4b42" # To have the bot sit on an object, right click and copy that object's uuid to here
# sim = "Fluffy" # The region name you want your bot in
# pos_x = 170
# pos_y = 185
# pos_z = 22
login_uri = "https://login.agni.lindenlab.com/cgi-bin/login.cgi"
grid_name = "agni"

[ircserver.freenode]
irc_server = "irc.freenode.net"
irc_port = 6667
irc_nick = "SinguRelay"
irc_username = "SinguRelay"

[ircchan.SingularitySL]
irc_server = "freenode" # [ircserver.<This>]
channel = "#SingularitySL"

# [slack.dummyserv]
# slack_key = "somekeyorsomething"

# [slackchannel.relay]
# slack_server = "dummyserv" # [slack.<This>]
# channel = "relay"

# [discord.discordbot]
# token = "bottoken" # create a bot here: https://discordapp.com/developers/applications/me, create a bot user, not public, click to reveal token.
# saferoles = ["comma","separated","role","names"] # These roles are unmentionable through relay
# devroles = ["comma","separated","roles"] # People in these roles can be mentioned over relay

# [discordchannel.discordrelay]
# discord_server = "dummyservid" # [discord.<This>]
# channel = relayid # example: 129471267412646

[bridge.SingularitySL]
ircchan = "SingularitySL" # [ircchan.<This>]
# slackchannel = "relay" # [slackchannel.<This>]
# discordchannel = "discordrelay" # [discordchannel.<This>]
grid_group = "4fa278be-b621-9447-0958-85af4b01cdab" # ID of your group on the grid or "local" if you want a local chat bridge
bot = "MyBot" # [bot.<This>]
